### ISSUE TITLE
How to run a command every weekend?

### ISSUE THREAD

**Issue by kunansy** [umputun/cronn#20]
The command: `docker run umputun/cronn:v1.0.0 /srv/cronn -c "0 6 * * 5,6 echo hello"` runs on Friday and Saturday, and the command `docker run umputun/cronn:v1.0.0 /srv/cronn -c "0 6 * * 6,7 echo hello"` crashes. Question: how can I set weekends if 5,6 is Friday and Saturday and 6,7 is not working at all?

**Comment by umputun** [comment]
If the issue you have with `0 6 * * 6,7` is invalid weekday (7) and running with logging, it will clearly show what is wrong here. Sun is `0`, not `7`

`WARN  can't load crontab file, can't add 0 6 * * 6,7, echo hello: can't parse 0 6 * * 6,7: end of range (7) above maximum (6): 7`

**Comment by kunansy** [comment]
Thanks, I'll try `6,0`
