### ISSUE TITLE
Cant make successful telegram notifications work

### ISSUE THREAD

**Issue by orthur** [umputun/cronn#26]
This command I use in a docker container

`./srv/cronn --notify.telegram-destinations=-100X --notify.telegram-token=TOKEN --notify.enabled-complete -c "@every 10s ls" --log.debug --log.enabled`

output

```
cronn v1.0.0-60181eb-20231027T14:34:14
2024/05/23 18:44:04 INFO  {app/main.go:113 main.main app} auto-update disabled
2024/05/23 18:44:04 DEBUG {notify/telegram.go:92 notify.NewTelegram notify} create new telegram notifier for api=https://api.telegram.org/bot, timeout=5s
2024/05/23 18:44:04 INFO  {service/service.go:124 service.(*Scheduler).schedule service} new cron, command "ls"
2024/05/23 18:44:04 INFO  {service/service.go:131 service.(*Scheduler).schedule service} first: 2024-05-23T18:44:14Z, "ls" (1)
2024/05/23 18:44:14 INFO  {service/service.go:173 service.(*Scheduler).jobFunc.func2 service} executing: "ls"
[...]
2024/05/23 18:44:14 INFO  {service/service.go:177 service.(*Scheduler).jobFunc.func2 service} completed ls
2024/05/23 18:44:14 INFO  {service/service.go:179 service.(*Scheduler).jobFunc.func2 service} next: 2024-05-23T18:44:24Z, "ls"
```

bot added as admin to public channel. bot has rights to post messages to the channel. i was able to post messages with example from https://github.com/go-pkgz/notify/tree/master?tab=readme-ov-file#telegram to test that bot can post messages.

how can I debug it further?

**Comment by paskal** [comment]
I can replicate it. I am looking into it.

**Comment by paskal** [comment]
I see that with `--notify.enabled-error`, an error notification comes, but with `--notify.enabled-complete`, a successful completion notification never comes. I'll fix that.
